disabled_rules: # rule identifiers to exclude from running
  - todo
  - line_length
  - identifier_name
  - type_name
  - nesting
  - valid_ibinspectable
  - private_over_fileprivate
  - multiple_closures_with_trailing_closure
  - switch_case_alignment

opt_in_rules:
  - empty_count
  - closure_end_indentation
  - first_where
  - operator_usage_whitespace
  - private_outlet
  - unneeded_parentheses_in_closure_argument
  - fatal_error_message

excluded:
  - TasksService

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning
force_try: warning
custom_rules:
  no_createdby:
    regex: "Created by.*"
    message: "All 'Created by...' must be removed from file header"
    severity: error
file_length:
  warning: 500
  error: 800
type_body_length:
  warning: 300
  error: 450
